name: magic_8_ball
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
#  flutter:
#    sdk: flutter
  flutter_web: any
  aiframework: ^1.0.7+12
  flutter_web_ui: any
  http: any
# cupertino_icons: ^0.1.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_web_test: any
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0


  test: ^1.3.4

flutter:

  uses-material-design: true

  assets:
    - images/

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
